spring:
  application:
    name: medsync-historico-api

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://${MONGO_USERNAME:medsync}:${MONGO_PASSWORD:medsync_password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:medsync_db}?authSource=admin}

  graphql:
    graphiql:
      enabled: true
    http:
      path: /graphql
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls

server:
  port: 8081

jwt:
  public:
    key: ${JWT_PUBLIC_KEY_PATH:certs/public_key.pem}

app:
  name: medsync-historico
  version: 1.0.0
