spring:
  application:
    name: medsync-historico-api

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://medsync:medsync_password@localhost:27017/medsync_db?authSource=admin}

  graphql:
    graphiql:
      enabled: true
    http:
      path: /graphql
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

server:
  port: 8081

app:
  name: medsync-historico
  version: 1.0.0
  rabbitmq:
    exchange-consultas: ex_consultas
    queue-historico: q_historico_consultas
    routing-key-historico: consulta.historico
